[gsoc] Conclusion Blog Post
lowRISC/lowrisc-web pull request #58
Opened 2020-09-04 17:10 UTC by lenary

This is the blog post, as translated from the Google Doc.

2020-09-06 13:54 UTC, vogelpi reviewed
Thanks @lenary for correcting and transferring this into a PR. This looks good to me, but the part on Flavien's project should also be cross-checked by @GregAC who has a better overview of what the final project status is.

2020-09-06 13:54 UTC, vogelpi commented on site/content/blog/gsoc-2020-conclusion.md
> +`gsoc-sim-mem` GitHub repository](https://github.com/lowRISC/gsoc-sim-mem).
@GregAC it would be great if you could have a quick look at this and make sure it accurately describes the current status of the codebase.

2020-09-07 08:42 UTC, GregAC requested changes

2020-09-07 08:42 UTC, GregAC commented on site/content/blog/gsoc-2020-conclusion.md
> +`gsoc-sim-mem` GitHub repository](https://github.com/lowRISC/gsoc-sim-mem).
```suggestion
All of Flavien's code, including documentation and a Verilator testbench can be found in [our
`gsoc-sim-mem` GitHub repository](https://github.com/lowRISC/gsoc-sim-mem).
```

FPGA stuff isn't quite working yet, there's some integration documentation but there's an outstanding issue so it still doesn't work. I think simplest to not mention the FPGA side of thing here.

2020-09-07 08:42 UTC, GregAC commented on site/content/blog/gsoc-2020-conclusion.md
> +by a separated Delay Calculator block that emulates a memory request scheduler.
```suggestion
by a separated Delay Calculator block that emulates a memory request scheduler and controller.
```

2020-09-09 18:31 UTC, lenary commented
Ok, this needs review from @asb and then it can go forward. I'll let him merge when he's back in the office.

2020-09-14 16:31 UTC, GregAC approved these changes

2020-09-14 17:07 UTC, merged

2020-09-14 17:09 UTC, GregAC commented
I did just force push a change to give it today's date rather than last week's date, but looked like I missed the merge. Probably not a big issue just felt it's a bit weird for posts to appear with dates in the past.

2020-09-14 17:11 UTC, asb commented
I agree - I actually pushed a commit a bit before your message that fixes the publish date to today :)